language: csharp
mono:
  - latest
env: 
  - VERSION=0.3.10
  - TRAVIS_NODE_VERSION="4"

solution: src/Soloco.RealTimeWeb.sln

addons:
  postgresql: "9.4"

install:
 - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh | DNX_BRANCH=dev sh && source ~/.dnx/dnvm/dnvm.sh
 - dnvm upgrade
 - dnu restore
  
before_script:
 - chmod +x ./scripts/build.sh ./scripts/run-tests.sh
 
script:
  - ./scripts/build.sh

after_failure:
  - ls -LR src/packages

  